version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      app_network:
        ipv4_address: 172.16.238.10

  web:
    build:
      context: ./backend
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn --workers 3 --bind 0.0.0.0:8000 backend.backend.wsgi:application
      "
    volumes:
      - ./backend:/app
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DB_NAME=todo_db
      - DB_USER=todo_user
      - DB_PASSWORD=todo_password
      - DB_HOST=db
      - DB_PORT=5432
    networks:
      app_network:
        ipv4_address: 172.16.238.11

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      app_network:
        ipv4_address: 172.16.238.12

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24
